import Foundation

/// V1 site catalogue — mirrors SITES array from chronicarum.html.
/// Extend with UNESCO JSON feed once backend is wired.
enum SiteData {
    static let all: [Site] = [
        Site(
            id: "colosseum",
            name: "Colosseum",
            location: "Rome, Italy",
            latitude: 41.89,
            longitude: 12.49,
            era: .classical,
            type: .wonder,
            tier: 5,
            builtDescription: "70–80 AD",
            civilisation: "Roman Empire",
            tagline: "Where 65,000 Romans roared as one",
            chapters: [
                Chapter(
                    id: "colosseum-ch1",
                    title: "Construction",
                    eyebrow: "70–80 AD",
                    heading: "Built by Slaves, for the People",
                    body: "<p>The Flavian Amphitheatre — named for the dynasty that built it — was commissioned by Emperor Vespasian in 70 AD and completed under his son Titus in 80 AD. Its construction required 100,000 prisoners of war brought back from the sack of Jerusalem, labouring for a decade to raise 100,000 cubic metres of travertine stone.</p>",
                    facts: [
                        Fact(label: "Capacity",   value: "50,000–80,000 spectators"),
                        Fact(label: "Height",     value: "48 metres (157 ft)"),
                        Fact(label: "Built",      value: "70–80 AD"),
                        Fact(label: "Material",   value: "Travertine limestone, tuff, brick"),
                    ]
                ),
            ],
            nearestAirport: "Rome Fiumicino (FCO)",
            bestTimeToVisit: "April–June or September–October",
            visaNote: "EU/Schengen — 90-day visa-free for most Western passports"
        ),
        Site(
            id: "machu-picchu",
            name: "Machu Picchu",
            location: "Cusco Region, Peru",
            latitude: -13.16,
            longitude: -72.54,
            era: .renaissance,
            type: .wonder,
            tier: 5,
            builtDescription: "c. 1450 AD",
            civilisation: "Inca Empire",
            tagline: "The city the Spanish never found",
            chapters: [],
            nearestAirport: "Alejandro Velasco Astete (CUZ)",
            bestTimeToVisit: "May–October (dry season)",
            visaNote: "Visa-free for most passports up to 90 days"
        ),
        Site(
            id: "angkor-wat",
            name: "Angkor Wat",
            location: "Siem Reap, Cambodia",
            latitude: 13.41,
            longitude: 103.87,
            era: .medieval,
            type: .sacred,
            tier: 5,
            builtDescription: "Early 12th century",
            civilisation: "Khmer Empire",
            tagline: "The largest religious structure ever built",
            chapters: [],
            nearestAirport: "Siem Reap International (REP)",
            bestTimeToVisit: "November–March",
            visaNote: "e-Visa available; 30-day single entry"
        ),
        Site(
            id: "petra",
            name: "Petra",
            location: "Ma'an Governorate, Jordan",
            latitude: 30.33,
            longitude: 35.44,
            era: .classical,
            type: .lostCity,
            tier: 5,
            builtDescription: "4th century BC – 2nd century AD",
            civilisation: "Nabataean Kingdom",
            tagline: "The rose-red city lost for a thousand years",
            chapters: [],
            nearestAirport: "King Hussein International (AQJ)",
            bestTimeToVisit: "March–May or September–November",
            visaNote: "Jordan Pass available; visa on arrival for most"
        ),
        Site(
            id: "acropolis",
            name: "Acropolis of Athens",
            location: "Athens, Greece",
            latitude: 37.97,
            longitude: 23.73,
            era: .classical,
            type: .wonder,
            tier: 5,
            builtDescription: "5th century BC",
            civilisation: "Athenian / Greek",
            tagline: "The rock where democracy was born",
            chapters: [],
            nearestAirport: "Athens International Eleftherios Venizelos (ATH)",
            bestTimeToVisit: "April–June or September–October",
            visaNote: "EU/Schengen"
        ),
        Site(
            id: "pompeii",
            name: "Pompeii",
            location: "Campania, Italy",
            latitude: 40.75,
            longitude: 14.49,
            era: .classical,
            type: .lostCity,
            tier: 5,
            builtDescription: "Founded 7th–6th century BC; destroyed 79 AD",
            civilisation: "Roman Empire",
            tagline: "Frozen in the ash of Vesuvius",
            chapters: [],
            nearestAirport: "Naples International (NAP)",
            bestTimeToVisit: "April–June or September–October",
            visaNote: "EU/Schengen"
        ),
        Site(
            id: "valley-of-kings",
            name: "Valley of the Kings",
            location: "Luxor, Egypt",
            latitude: 25.74,
            longitude: 32.60,
            era: .ancient,
            type: .treasure,
            tier: 5,
            builtDescription: "16th–11th century BC",
            civilisation: "New Kingdom Egypt",
            tagline: "Where pharaohs slept for eternity",
            chapters: [],
            nearestAirport: "Luxor International (LXR)",
            bestTimeToVisit: "October–April",
            visaNote: "e-Visa available online"
        ),
        Site(
            id: "edinburgh-castle",
            name: "Edinburgh Castle",
            location: "Edinburgh, Scotland",
            latitude: 55.95,
            longitude: -3.20,
            era: .medieval,
            type: .castle,
            tier: 4,
            builtDescription: "12th century (fortress from 2nd millennium BC)",
            civilisation: "Kingdom of Scotland",
            tagline: "900 years of Scottish history in stone",
            chapters: [],
            nearestAirport: "Edinburgh Airport (EDI)",
            bestTimeToVisit: "May–September",
            visaNote: "UK — ETA required for most non-UK/Irish visitors from 2024"
        ),
        Site(
            id: "alhambra",
            name: "Alhambra",
            location: "Granada, Spain",
            latitude: 37.18,
            longitude: -3.59,
            era: .medieval,
            type: .wonder,
            tier: 5,
            builtDescription: "13th–14th century AD",
            civilisation: "Nasrid Emirate of Granada",
            tagline: "The last jewel of Islamic Spain",
            chapters: [],
            nearestAirport: "Federico García Lorca Airport (GRX)",
            bestTimeToVisit: "April–June or September–October",
            visaNote: "EU/Schengen"
        ),
        Site(
            id: "terracotta-army",
            name: "Terracotta Army",
            location: "Xi'an, Shaanxi, China",
            latitude: 34.38,
            longitude: 109.27,
            era: .ancient,
            type: .treasure,
            tier: 5,
            builtDescription: "c. 246–208 BC",
            civilisation: "Qin Dynasty",
            tagline: "8,000 warriors for an emperor's afterlife",
            chapters: [],
            nearestAirport: "Xi'an Xianyang International (XIY)",
            bestTimeToVisit: "March–May or September–November",
            visaNote: "Visa-free transit for qualifying nationalities; standard visa otherwise"
        ),
        Site(
            id: "stonehenge",
            name: "Stonehenge",
            location: "Wiltshire, England",
            latitude: 51.18,
            longitude: -1.83,
            era: .ancient,
            type: .sacred,
            tier: 5,
            builtDescription: "3000–1500 BC",
            civilisation: "Neolithic / Bronze Age Britons",
            tagline: "The mystery the millennia could not answer",
            chapters: [],
            nearestAirport: "London Heathrow (LHR) or Southampton (SOU)",
            bestTimeToVisit: "May–September (summer solstice access special)",
            visaNote: "UK — ETA required for most non-UK/Irish visitors from 2024"
        ),
        Site(
            id: "chichen-itza",
            name: "Chichen Itza",
            location: "Yucatán, Mexico",
            latitude: 20.68,
            longitude: -88.57,
            era: .medieval,
            type: .wonder,
            tier: 5,
            builtDescription: "c. 600–1200 AD",
            civilisation: "Maya Civilisation",
            tagline: "Where the serpent descends at equinox",
            chapters: [],
            nearestAirport: "Cancún International (CUN)",
            bestTimeToVisit: "December–April",
            visaNote: "Visa-free for most Western passports up to 180 days"
        ),
    ]
}
