import Foundation

/// Static timeline data — mirrors TIMELINE_DATA from chronicarum.html.
/// Replace with a JSON bundle or remote fetch when the dataset grows.
enum TimelineData {
    static let periods: [TimelinePeriod] = [
        TimelinePeriod(
            id: "500bc",
            year: -500,
            label: "500 BC",
            subtitle: "Classical Antiquity — Rise of Persia & Greece",
            empires: [
                Empire(id: "achaemenid", name: "Achaemenid Persian Empire", color: "#9B59B6",
                       polygon: [[28,42],[44,43],[55,40],[68,37],[72,35],[70,25],[57,22],[44,22],[36,22],[32,26],[32,33],[26,34]],
                       labelLongitude: 52, labelLatitude: 32),
                Empire(id: "greek-states", name: "Greek City-States", color: "#2980B9",
                       polygon: [[20,42],[26,42],[28,38],[22,36],[20,38]],
                       labelLongitude: 23, labelLatitude: 39),
                Empire(id: "carthage", name: "Carthaginian Empire", color: "#C0392B",
                       polygon: [[-2,36],[12,38],[16,34],[10,31],[0,33],[-5,35]],
                       labelLongitude: 5, labelLatitude: 34),
                Empire(id: "celtic", name: "Celtic Europe", color: "#27AE60",
                       polygon: [[-10,58],[-3,58],[16,55],[18,48],[10,44],[3,44],[-2,44],[-10,48]],
                       labelLongitude: 4, labelLatitude: 50),
            ],
            regionLabels: [
                RegionLabel(id: "hellas",  name: "HELLAS",       longitude: 23,  latitude: 38),
                RegionLabel(id: "persia",  name: "PERSIA",       longitude: 52,  latitude: 32),
                RegionLabel(id: "egypt",   name: "AEGYPTUS",     longitude: 31,  latitude: 27),
                RegionLabel(id: "meso",    name: "MESOPOTAMIA",  longitude: 44,  latitude: 34),
                RegionLabel(id: "bactria", name: "BACTRIA",      longitude: 67,  latitude: 37),
                RegionLabel(id: "india",   name: "INDIA",        longitude: 78,  latitude: 22),
                RegionLabel(id: "scythia", name: "SCYTHIA",      longitude: 42,  latitude: 50),
                RegionLabel(id: "gaul",    name: "GAUL",         longitude: 2,   latitude: 47),
                RegionLabel(id: "iberia",  name: "IBERIA",       longitude: -4,  latitude: 40),
                RegionLabel(id: "carthago",name: "CARTHAGO",     longitude: 8,   latitude: 34),
                RegionLabel(id: "kush",    name: "KUSH",         longitude: 32,  latitude: 18),
                RegionLabel(id: "qin",     name: "QIN DYNASTY",  longitude: 110, latitude: 34),
            ],
            nameChanges: []
        ),
        TimelinePeriod(
            id: "100ad",
            year: 100,
            label: "100 AD",
            subtitle: "Pax Romana — The Roman Empire at Its Height",
            empires: [
                Empire(id: "rome", name: "Roman Empire", color: "#E74C3C",
                       polygon: [[-9,44],[-9,37],[-6,36],[10,37],[24,32],[35,24],[35,32],[38,34],[44,37],[44,41],[40,43],[32,47],[29,46],[17,48],[8,47],[8,52],[5,52],[3,51],[-5,48],[-2,44]],
                       labelLongitude: 13, labelLatitude: 42),
                Empire(id: "rome-britain", name: "Roman Britain", color: "#E74C3C",
                       polygon: [[-5,58],[0,58],[2,52],[2,51],[-3,50],[-5,51],[-4,54]],
                       labelLongitude: -2, labelLatitude: 53),
                Empire(id: "parthia", name: "Parthian Empire", color: "#E67E22",
                       polygon: [[44,37],[60,40],[68,37],[72,35],[68,22],[57,22],[44,22],[36,22],[38,34]],
                       labelLongitude: 55, labelLatitude: 30),
                Empire(id: "han", name: "Han Dynasty", color: "#1ABC9C",
                       polygon: [[100,50],[130,50],[130,22],[112,22],[100,20],[80,30],[80,40],[90,45]],
                       labelLongitude: 110, labelLatitude: 36),
            ],
            regionLabels: [
                RegionLabel(id: "roma",        name: "ROMA / ITALIA",   longitude: 13,  latitude: 42),
                RegionLabel(id: "gallia",      name: "GALLIA",          longitude: 2,   latitude: 47),
                RegionLabel(id: "hispania",    name: "HISPANIA",        longitude: -4,  latitude: 40),
                RegionLabel(id: "britannia",   name: "BRITANNIA",       longitude: -2,  latitude: 53),
                RegionLabel(id: "aegyptus",    name: "AEGYPTUS",        longitude: 31,  latitude: 27),
                RegionLabel(id: "syria",       name: "SYRIA",           longitude: 36,  latitude: 34),
                RegionLabel(id: "mesopotamia", name: "MESOPOTAMIA",     longitude: 44,  latitude: 34),
                RegionLabel(id: "parthia-lbl", name: "PARTHIA",         longitude: 55,  latitude: 32),
                RegionLabel(id: "india-lbl",   name: "INDIA",           longitude: 78,  latitude: 22),
                RegionLabel(id: "sina",        name: "SINA (HAN)",      longitude: 110, latitude: 36),
                RegionLabel(id: "germania",    name: "GERMANIA",        longitude: 14,  latitude: 52),
                RegionLabel(id: "sarmatia",    name: "SARMATIA",        longitude: 40,  latitude: 50),
            ],
            nameChanges: []
        ),
        TimelinePeriod(
            id: "650ad",
            year: 650,
            label: "650 AD",
            subtitle: "The Caliphate Spreads — Islam Changes the World",
            empires: [
                Empire(id: "umayyad", name: "Umayyad Caliphate", color: "#27AE60",
                       polygon: [[-9,36],[-6,36],[10,36],[25,33],[36,34],[44,38],[60,40],[68,37],[72,35],[68,22],[57,22],[44,22],[36,22],[32,26],[24,32],[10,34],[0,34],[-5,34]],
                       labelLongitude: 30, labelLatitude: 28),
                Empire(id: "byzantine", name: "Byzantine Empire", color: "#2980B9",
                       polygon: [[24,38],[36,38],[42,42],[44,42],[44,40],[40,43],[32,47],[28,42],[22,38]],
                       labelLongitude: 32, labelLatitude: 39),
                Empire(id: "tang", name: "Tang Dynasty", color: "#E74C3C",
                       polygon: [[80,50],[120,50],[130,40],[122,22],[110,20],[100,20],[85,28],[80,36]],
                       labelLongitude: 106, labelLatitude: 36),
                Empire(id: "frankish", name: "Frankish Kingdom", color: "#F39C12",
                       polygon: [[-5,50],[16,55],[18,48],[8,44],[3,44],[-2,44],[-5,48]],
                       labelLongitude: 5, labelLatitude: 49),
            ],
            regionLabels: [
                RegionLabel(id: "al-andalus", name: "AL-ANDALUS",     longitude: -4,  latitude: 38),
                RegionLabel(id: "ifriqiya",   name: "IFRIQIYA",       longitude: 10,  latitude: 34),
                RegionLabel(id: "misr",       name: "MISR (EGYPT)",   longitude: 31,  latitude: 27),
                RegionLabel(id: "sham",       name: "BILAD AL-SHAM",  longitude: 36,  latitude: 32),
                RegionLabel(id: "jazira",     name: "JAZIRA",         longitude: 44,  latitude: 34),
                RegionLabel(id: "khurasan",   name: "KHURASAN",       longitude: 60,  latitude: 34),
                RegionLabel(id: "byzantium",  name: "BYZANTIUM",      longitude: 32,  latitude: 39),
                RegionLabel(id: "frankia",    name: "FRANKIA",        longitude: 5,   latitude: 49),
                RegionLabel(id: "tang-china", name: "TANG CHINA",     longitude: 106, latitude: 36),
                RegionLabel(id: "bulgaria",   name: "BULGARIA",       longitude: 24,  latitude: 46),
                RegionLabel(id: "saxony",     name: "SAXONY",         longitude: 14,  latitude: 52),
                RegionLabel(id: "arabia",     name: "ARABIA",         longitude: 24,  latitude: 22),
            ],
            nameChanges: [
                NameChange(id: "rome-byzantium",           oldName: "ROME",           newName: "BYZANTIUM", year: 330),
                NameChange(id: "constantinople-byzantium", oldName: "CONSTANTINOPLE", newName: "BYZANTIUM", year: 337),
            ]
        ),
        TimelinePeriod(
            id: "1250ad",
            year: 1250,
            label: "1250 AD",
            subtitle: "The Mongol World Empire — Largest in History",
            empires: [
                Empire(id: "mongol", name: "Mongol Empire", color: "#8E6914",
                       polygon: [[22,48],[30,55],[60,56],[90,57],[120,55],[135,52],[135,30],[120,22],[106,18],[80,26],[68,22],[44,22],[36,34],[32,46]],
                       labelLongitude: 82, labelLatitude: 46),
                Empire(id: "latin-europe", name: "Latin/European Kingdoms", color: "#34495E",
                       polygon: [[-10,58],[-2,58],[18,60],[18,50],[10,44],[3,43],[-2,44],[-10,50]],
                       labelLongitude: 4, labelLatitude: 50),
                Empire(id: "mamluk", name: "Mamluk Egypt", color: "#C0392B",
                       polygon: [[24,22],[36,22],[38,30],[36,34],[25,33]],
                       labelLongitude: 30, labelLatitude: 27),
            ],
            regionLabels: [
                RegionLabel(id: "mongol-lbl",  name: "MONGOL EMPIRE",     longitude: 82,  latitude: 46),
                RegionLabel(id: "golden-horde",name: "GOLDEN HORDE",      longitude: 50,  latitude: 52),
                RegionLabel(id: "ilkhanate",   name: "ILKHANATE",         longitude: 54,  latitude: 36),
                RegionLabel(id: "chagatai",    name: "CHAGATAI KHANATE",  longitude: 76,  latitude: 42),
                RegionLabel(id: "france",      name: "FRANCE",            longitude: 5,   latitude: 49),
                RegionLabel(id: "hre",         name: "HOLY ROMAN EMPIRE", longitude: 12,  latitude: 50),
                RegionLabel(id: "england",     name: "ENGLAND",           longitude: -2,  latitude: 53),
                RegionLabel(id: "poland",      name: "POLAND",            longitude: 20,  latitude: 52),
                RegionLabel(id: "mamluk-lbl",  name: "MAMLUK EGYPT",      longitude: 30,  latitude: 27),
                RegionLabel(id: "delhi",       name: "DELHI SULTANATE",   longitude: 78,  latitude: 28),
                RegionLabel(id: "song",        name: "SONG DYNASTY",      longitude: 112, latitude: 30),
            ],
            nameChanges: [
                NameChange(id: "persia-ilkhanate", oldName: "PERSIA",      newName: "ILKHANATE (Mongol)",   year: 1256),
                NameChange(id: "rus-horde",        oldName: "RUS",         newName: "GOLDEN HORDE (Mongol)", year: 1240),
                NameChange(id: "jin-mongol",       oldName: "CHINA (Jin)", newName: "MONGOL KHANATE",        year: 1234),
            ]
        ),
        TimelinePeriod(
            id: "1500ad",
            year: 1500,
            label: "1500 AD",
            subtitle: "Ottoman Supremacy & the Age of Exploration",
            empires: [
                Empire(id: "ottoman", name: "Ottoman Empire", color: "#C0392B",
                       polygon: [[-2,36],[12,34],[30,32],[36,34],[44,38],[44,43],[34,47],[28,47],[20,46],[14,44],[20,40],[22,38],[26,38],[10,38]],
                       labelLongitude: 30, labelLatitude: 38),
                Empire(id: "safavid", name: "Safavid Persia", color: "#9B59B6",
                       polygon: [[44,38],[60,40],[68,37],[72,35],[68,22],[57,22],[44,22],[38,30],[38,34]],
                       labelLongitude: 54, labelLatitude: 32),
                Empire(id: "ming", name: "Ming Dynasty", color: "#1ABC9C",
                       polygon: [[100,42],[122,42],[130,30],[122,22],[110,18],[100,20],[90,28],[88,36]],
                       labelLongitude: 108, labelLatitude: 34),
                Empire(id: "habsburg-spain", name: "Habsburg Spain", color: "#F39C12",
                       polygon: [[-9,44],[-9,37],[-6,36],[3,36],[8,44],[16,50],[16,44],[8,42],[-2,44]],
                       labelLongitude: -2, labelLatitude: 40),
                Empire(id: "aztec", name: "Aztec Empire", color: "#27AE60",
                       polygon: [[-102,22],[-88,22],[-88,16],[-95,14],[-102,18]],
                       labelLongitude: -96, labelLatitude: 18),
                Empire(id: "inca", name: "Inca Empire", color: "#E67E22",
                       polygon: [[-80,-5],[-70,-5],[-68,-18],[-70,-40],[-78,-40],[-80,-18]],
                       labelLongitude: -74, labelLatitude: -16),
            ],
            regionLabels: [
                RegionLabel(id: "ottoman-lbl",  name: "OTTOMAN EMPIRE",    longitude: 30,  latitude: 38),
                RegionLabel(id: "safavid-lbl",  name: "SAFAVID PERSIA",    longitude: 54,  latitude: 32),
                RegionLabel(id: "ming-lbl",     name: "MING CHINA",        longitude: 108, latitude: 34),
                RegionLabel(id: "castile",      name: "CASTILE",           longitude: -2,  latitude: 40),
                RegionLabel(id: "hre",          name: "HOLY ROMAN EMPIRE", longitude: 12,  latitude: 50),
                RegionLabel(id: "muscovy",      name: "MUSCOVY",           longitude: 36,  latitude: 56),
                RegionLabel(id: "aztec-lbl",    name: "AZTEC",             longitude: -96, latitude: 18),
                RegionLabel(id: "inca-lbl",     name: "INCA",              longitude: -74, latitude: -16),
                RegionLabel(id: "portugal",     name: "PORTUGAL",          longitude: -8,  latitude: 39),
                RegionLabel(id: "france",       name: "FRANCE",            longitude: 2,   latitude: 47),
                RegionLabel(id: "england",      name: "ENGLAND",           longitude: -2,  latitude: 53),
                RegionLabel(id: "vijayanagara", name: "VIJAYANAGARA",      longitude: 78,  latitude: 22),
            ],
            nameChanges: [
                NameChange(id: "byzantium-ottoman",     oldName: "BYZANTIUM",         newName: "OTTOMAN EMPIRE", year: 1453),
                NameChange(id: "constantinople-istanbul", oldName: "CONSTANTINOPLE",  newName: "ISTANBUL",       year: 1453),
                NameChange(id: "granada-castile",       oldName: "GRANADA (Moorish)", newName: "CASTILE",        year: 1492),
            ]
        ),
        TimelinePeriod(
            id: "1800ad",
            year: 1800,
            label: "1800 AD",
            subtitle: "Napoleon & the British Empire — The World Divided",
            empires: [
                Empire(id: "british-india", name: "British (India)", color: "#C0392B",
                       polygon: [[68,36],[88,28],[92,22],[88,8],[80,8],[72,20],[68,28]],
                       labelLongitude: 80, labelLatitude: 22),
                Empire(id: "british-australia", name: "British (Australia)", color: "#C0392B",
                       polygon: [[114,-22],[154,-22],[154,-38],[138,-38],[126,-34],[114,-34]],
                       labelLongitude: 134, labelLatitude: -28),
                Empire(id: "french-napoleon", name: "French Empire (Napoleon)", color: "#2980B9",
                       polygon: [[-5,50],[16,55],[18,48],[12,44],[6,44],[3,43],[-5,48]],
                       labelLongitude: 5, labelLatitude: 48),
                Empire(id: "russian", name: "Russian Empire", color: "#27AE60",
                       polygon: [[22,70],[110,70],[120,62],[140,58],[140,40],[80,40],[44,42],[30,55],[22,62]],
                       labelLongitude: 72, labelLatitude: 58),
                Empire(id: "ottoman", name: "Ottoman Empire", color: "#E67E22",
                       polygon: [[-2,36],[12,34],[30,32],[36,34],[44,38],[42,42],[34,47],[28,47],[22,46],[14,44],[20,40],[22,38],[26,38],[10,38]],
                       labelLongitude: 28, labelLatitude: 38),
                Empire(id: "qing", name: "Qing Dynasty", color: "#1ABC9C",
                       polygon: [[80,44],[134,44],[134,20],[110,18],[100,20],[90,28],[80,36]],
                       labelLongitude: 108, labelLatitude: 36),
            ],
            regionLabels: [
                RegionLabel(id: "british-india-lbl", name: "BRITISH INDIA",        longitude: 80,   latitude: 22),
                RegionLabel(id: "nsw",               name: "NEW S. WALES",         longitude: 134,  latitude: -28),
                RegionLabel(id: "france",            name: "FRANCE",               longitude: 5,    latitude: 48),
                RegionLabel(id: "russia",            name: "RUSSIA",               longitude: 72,   latitude: 58),
                RegionLabel(id: "ottoman-lbl",       name: "OTTOMAN EMPIRE",       longitude: 28,   latitude: 38),
                RegionLabel(id: "persia",            name: "PERSIA",               longitude: 56,   latitude: 32),
                RegionLabel(id: "qing-lbl",          name: "QING DYNASTY",         longitude: 108,  latitude: 36),
                RegionLabel(id: "usa",               name: "UNITED STATES",        longitude: -100, latitude: 40),
                RegionLabel(id: "spanish-america",   name: "SPANISH AMERICA",      longitude: -66,  latitude: -10),
                RegionLabel(id: "prussia",           name: "PRUSSIA",              longitude: 28,   latitude: 52),
                RegionLabel(id: "austria",           name: "AUSTRIA",              longitude: 14,   latitude: 42),
                RegionLabel(id: "poland",            name: "POLAND (partitioned)", longitude: 20,   latitude: 56),
            ],
            nameChanges: [
                NameChange(id: "persia-qajar",    oldName: "PERSIA",     newName: "PERSIA (Qajar Dynasty)",        year: 1796),
                NameChange(id: "newfrance-canada", oldName: "NEW FRANCE", newName: "UPPER/LOWER CANADA (British)", year: 1763),
            ]
        ),
        TimelinePeriod(
            id: "1920ad",
            year: 1920,
            label: "1920 AD",
            subtitle: "Peak of European Colonial Rule — The World Renamed",
            empires: [
                Empire(id: "british-empire", name: "British Empire", color: "#C0392B",
                       polygon: [[28,-12],[40,-12],[40,4],[30,4],[24,4],[22,14],[36,22],[35,8],[30,-10]],
                       labelLongitude: 32, labelLatitude: -2),
                Empire(id: "british-safrica", name: "British S. Africa", color: "#C0392B",
                       polygon: [[14,-18],[36,-18],[36,-34],[26,-34],[16,-34],[14,-26]],
                       labelLongitude: 26, labelLatitude: -26),
                Empire(id: "british-india", name: "British India", color: "#C0392B",
                       polygon: [[68,36],[88,28],[92,22],[88,8],[80,8],[72,20],[68,28]],
                       labelLongitude: 80, labelLatitude: 22),
                Empire(id: "french-empire", name: "French Empire", color: "#2980B9",
                       polygon: [[-18,28],[16,28],[10,10],[8,4],[-2,4],[-18,16]],
                       labelLongitude: -2, labelLatitude: 18),
                Empire(id: "french-nafrica", name: "French N. Africa", color: "#2980B9",
                       polygon: [[-2,36],[10,36],[15,33],[10,10],[-2,15],[-18,28],[-18,36]],
                       labelLongitude: 4, labelLatitude: 30),
            ],
            regionLabels: [
                RegionLabel(id: "rhodesia",      name: "RHODESIA",             longitude: 30,  latitude: -16),
                RegionLabel(id: "gold-coast",    name: "GOLD COAST",           longitude: 8,   latitude: -1),
                RegionLabel(id: "nigeria",       name: "NIGERIA (Br.)",        longitude: 6,   latitude: 10),
                RegionLabel(id: "french-wafrica",name: "FRENCH W. AFRICA",     longitude: -4,  latitude: 14),
                RegionLabel(id: "tanganyika",    name: "TANGANYIKA",           longitude: 36,  latitude: -4),
                RegionLabel(id: "abyssinia",     name: "ABYSSINIA",            longitude: 39,  latitude: 9),
                RegionLabel(id: "british-india-lbl", name: "BRITISH INDIA",    longitude: 80,  latitude: 22),
                RegionLabel(id: "siam",          name: "SIAM",                 longitude: 101, latitude: 15),
                RegionLabel(id: "dei",           name: "DUTCH EAST INDIES",    longitude: 117, latitude: -4),
                RegionLabel(id: "indochina",     name: "FRENCH INDOCHINA",     longitude: 107, latitude: 16),
                RegionLabel(id: "ceylon",        name: "CEYLON",               longitude: 81,  latitude: 8),
                RegionLabel(id: "mesopotamia",   name: "MESOPOTAMIA",          longitude: 44,  latitude: 34),
                RegionLabel(id: "persia",        name: "PERSIA",               longitude: 56,  latitude: 32),
                RegionLabel(id: "palestine",     name: "PALESTINE (Mandate)",  longitude: 35,  latitude: 31),
                RegionLabel(id: "iraq",          name: "IRAQ (Mandate)",       longitude: 34,  latitude: 44),
            ],
            nameChanges: [
                NameChange(id: "rhodesia-zimbabwe",   oldName: "RHODESIA",            newName: "ZIMBABWE",                  year: 1980),
                NameChange(id: "goldcoast-ghana",     oldName: "GOLD COAST",          newName: "GHANA",                     year: 1957),
                NameChange(id: "tanganyika-tanzania", oldName: "TANGANYIKA",          newName: "TANZANIA",                  year: 1964),
                NameChange(id: "abyssinia-ethiopia",  oldName: "ABYSSINIA",           newName: "ETHIOPIA (restored)",       year: 1941),
                NameChange(id: "siam-thailand",       oldName: "SIAM",                newName: "THAILAND",                  year: 1939),
                NameChange(id: "dei-indonesia",       oldName: "DUTCH EAST INDIES",   newName: "INDONESIA",                 year: 1945),
                NameChange(id: "indochina-split",     oldName: "FRENCH INDOCHINA",    newName: "VIETNAM / LAOS / CAMBODIA", year: 1954),
                NameChange(id: "ceylon-srilanka",     oldName: "CEYLON",              newName: "SRI LANKA",                 year: 1972),
                NameChange(id: "persia-iran",         oldName: "PERSIA",              newName: "IRAN",                      year: 1935),
                NameChange(id: "mesopotamia-iraq",    oldName: "MESOPOTAMIA",         newName: "IRAQ",                      year: 1932),
                NameChange(id: "palestine-split",     oldName: "PALESTINE (Mandate)", newName: "ISRAEL + JORDAN",           year: 1948),
                NameChange(id: "india-partition",     oldName: "BRITISH INDIA",       newName: "INDIA + PAKISTAN",          year: 1947),
            ]
        ),
    ]
}
